### ISSUE TITLE
fastchan is missing platformdirs 3.10.0

### ISSUE THREAD

**Issue by sethfri** [fastai/fastconda#37]
I tried to run `mamba install -c fastchan fastai` but it fails, hitting a 404 error in trying to download platformdirs version 3.10.0 (error below). Looking at Anaconda, it looks like the latest platformdirs version in fastchan is indeed [3.9.1](https://anaconda.org/fastchan/platformdirs) instead of 3.10.0, but it is [3.11.0 in conda-forge](https://anaconda.org/conda-forge/platformdirs).

```
Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/fastchan/noarch/platformdirs-3.10.0-pyhd8ed1ab_0.conda] 17 bytes

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/mamba/mamba.py", line 754, in do_call
        exit_code = install(args, parser, "install")
      File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/mamba/mamba.py", line 588, in install
        transaction.fetch_extract_packages()
    RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/fastchan/noarch/platformdirs-3.10.0-pyhd8ed1ab_0.conda] 17 bytes
```

**Comment by sethfri** [comment]
Solved in #38!
