### ISSUE TITLE
setupconda and condabuild have been failing for 3 months

### ISSUE THREAD

**Issue by sethfri** [fastai/fastconda#38]
Hi @jph00! It looks like the `setupconda` and `condabuild` workflows have been failing for ~3 months. The last time I can see them running successfully consistently is 20 pages back in the [workflow runs](https://github.com/fastai/fastconda/actions?page=20).

I believe this might be why I'm seeing the issue I'm seeing in https://github.com/fastai/fastconda/issues/37 where `fastchan` doesn't have the latest version of `platformdirs` and fails `fastai` installation.

Do you mind taking a look at getting the workflows running again? Thanks for all you do! The fast.ai course has been a great help so far

**Comment by sethfri** [comment]
@jph00 Digging into the build logs, it actually looks like the `setupconda` workflow is running into the same thing I hit in #37. It's hitting a 404 when trying to pull version 3.10 of `platformdirs`.

Looking at the [Anaconda page](https://anaconda.org/fastchan/platformdirs/files) for `fastchan/platformdirs`, it actually does look like something is busted here. fastchan ostensibly has a `platformdirs` 3.10 that's 19.4 KB, but when you try to click on the link to download it [here](https://anaconda.org/fastchan/platformdirs/3.10.0/download/noarch/platformdirs-3.10.0-pyhd8ed1ab_0.conda), you get a 404. The version isn't actually there.

Would it be possible for you to manually take down fastchan's `platformdirs` version 3.10? Something seems to be misconfigured on Anaconda. I assume it will then get reuploaded by the GitHub Actions?

**Comment by sethfri** [comment]
@jph00 Seems to work on [my fork](https://github.com/sethfri/fastconda/actions/runs/6446108447/job/17500868671)! That solves `setupconda`, but `condabuild` is still failing and I have no idea why. The traceback in the logs is unfortunately quite nondescriptive:

```
Traceback (most recent call last):
    File "/home/runner/work/fastconda/fastconda/build.py", line 63, in <module>
      def main(
    File "/usr/share/miniconda3/envs/test/lib/python3.10/site-packages/fastcore/script.py", line 125, in call_parse
      return _f()
    File "/usr/share/miniconda3/envs/test/lib/python3.10/site-packages/fastcore/script.py", line 119, in _f
      return tfunc(**merge(args, args_from_prog(func, xtra)))
    File "/home/runner/work/fastconda/fastconda/build.py", line 72, in main
      with actions_group(f'Build {name}'): print(run(f'conda build {name} {args}'))
    File "/usr/share/miniconda3/envs/test/lib/python3.10/site-packages/fastcore/xtras.py", line 207, in run
      if res.returncode: raise IOError(stdout)
  OSError: Adding in variants from internal_defaults
```

**Comment by sethfri** [comment]
I tried adding more verbose logging on my fork [here](https://github.com/sethfri/fastconda/actions/runs/6446079052/job/17500804412), but it doesn't give me anything else. If you have any general Python debugging tips — I'm new to Python but not new to software — I'm happy to continue taking a look
